# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51ce3fe407aedc691d080c4de96bb4ecd92b7cb4a17b280c54e6aa1cd8389f3e15be3905b0bba12c559a253269fe9429de22cfa59dc3fb7430fb8d5691ebf787

test:
  secret_key_base: 2dc5a3b45470b996af81e8f7f00d0553004565c9b1eb97a75b05e8eb2552b96ed18669a551880acd7760cc4f7fe195522f17d1ed4740bfe8bbd4bc9453eb0173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
