# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5a92950fe5436c9cca9914f6adbbe4661db2a3d6ca5db920fc2529f24848bfe9b179bf68c344438e5bb8886861d28d423deef4e2364fb380c0e2bb21ae6e2d1

test:
  secret_key_base: 5d099417f01a1c036a68534295850f11a9b5515206b2af0d3f6c32540f47070ba1abb2c5924b6ae260974405421f02ffc0ffbbe194f38fcd0ae0b34cca17d22e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
